# Generated by Django 4.0 on 2022-10-14 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teaAdmin', '0003_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt1', models.CharField(max_length=400)),
                ('opt2', models.CharField(max_length=400)),
                ('opt3', models.CharField(max_length=400)),
                ('opt4', models.CharField(max_length=400)),
                ('ans', models.IntegerField()),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaAdmin.questions')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaAdmin.topics')),
            ],
        ),
    ]
