# Generated by Django 4.0 on 2022-10-14 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaAdmin', '0004_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='questions',
            new_name='question',
        ),
    ]
